//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NWLabs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Compound
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Compound()
        {
            this.Sequences = new HashSet<Sequence>();
        }
    
        public int LTNumber { get; set; }
        public string Name { get; set; }
        public decimal Quant_Mg { get; set; }
        public Nullable<System.DateTime> ArrivalDate { get; set; }
        public Nullable<int> RecievedByEmpID { get; set; }
        public string DueDate { get; set; }
        public decimal MTD { get; set; }
        public int AccountID { get; set; }
        public Nullable<bool> Active { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sequence> Sequences { get; set; }
    }
}
