//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NWLabs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Invoice()
        {
            this.Invoice_Payments = new HashSet<Invoice_Payments>();
        }
    
        public int InvoiceID { get; set; }
        public Nullable<int> TestMaterialID { get; set; }
        public Nullable<int> EmployeeTestID { get; set; }
        public Nullable<int> BasePriceID { get; set; }
        public Nullable<decimal> InvoiceTotal { get; set; }
        public Nullable<System.DateTime> PaymentDueDate { get; set; }
        public Nullable<System.DateTime> EarlyPaymentDueDate { get; set; }
        public Nullable<decimal> DiscountRate { get; set; }
        public Nullable<int> OrderID { get; set; }
    
        public virtual Base_Prices Base_Prices { get; set; }
        public virtual Employee_Tests Employee_Tests { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Invoice_Payments> Invoice_Payments { get; set; }
        public virtual Order Order { get; set; }
        public virtual Test_Materials Test_Materials { get; set; }
    }
}
