//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NWLabs.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NWlabsContext : DbContext
    {
        public NWlabsContext()
            : base("name=NWlabsContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Account> Accounts { get; set; }
        public virtual DbSet<Assay> Assays { get; set; }
        public virtual DbSet<Base_Prices> Base_Prices { get; set; }
        public virtual DbSet<Compound> Compounds { get; set; }
        public virtual DbSet<Contact> Contacts { get; set; }
        public virtual DbSet<Credential> Credentials { get; set; }
        public virtual DbSet<Employee_Tests> Employee_Tests { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<Invoice_Payments> Invoice_Payments { get; set; }
        public virtual DbSet<Invoice> Invoices { get; set; }
        public virtual DbSet<Material> Materials { get; set; }
        public virtual DbSet<Order_Details> Order_Details { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<Payment> Payments { get; set; }
        public virtual DbSet<Prereq_Test> Prereq_Test { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<Sequence> Sequences { get; set; }
        public virtual DbSet<Solvent> Solvents { get; set; }
        public virtual DbSet<Status> Status { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Test_Materials> Test_Materials { get; set; }
        public virtual DbSet<Test_Order_Details> Test_Order_Details { get; set; }
        public virtual DbSet<Test> Tests { get; set; }
        public virtual DbSet<Title> Titles { get; set; }
    }
}
