//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NWLabs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order_Details
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order_Details()
        {
            this.Test_Order_Details = new HashSet<Test_Order_Details>();
        }
    
        public int OrderDetailID { get; set; }
        public Nullable<int> OrderID { get; set; }
        public Nullable<int> AssayID { get; set; }
        public Nullable<int> SeqID { get; set; }
        public Nullable<int> OrderDetailStatus { get; set; }
        public Nullable<bool> Authorized { get; set; }
        public string DataReport { get; set; }
    
        public virtual Assay Assay { get; set; }
        public virtual Order Order { get; set; }
        public virtual Sequence Sequence { get; set; }
        public virtual Status Status { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Test_Order_Details> Test_Order_Details { get; set; }
    }
}
