//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NWLabs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prereq_Test
    {
        public int PrereqTestID { get; set; }
        public int TestID { get; set; }
        public Nullable<int> ConditionaltestID { get; set; }
    
        public virtual Test Test { get; set; }
        public virtual Test Test1 { get; set; }
    }
}
