//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NWLabs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sequence
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sequence()
        {
            this.Order_Details = new HashSet<Order_Details>();
        }
    
        public int SeqID { get; set; }
        public int LTNumber { get; set; }
        public int SeqCode { get; set; }
        public string SampleAppearance { get; set; }
        public decimal DocumentedWeight { get; set; }
        public decimal MolecularMass { get; set; }
        public decimal ActualWeight { get; set; }
    
        public virtual Compound Compound { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order_Details> Order_Details { get; set; }
    }
}
