//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NWLabs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Test_Order_Details
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Test_Order_Details()
        {
            this.Employee_Tests = new HashSet<Employee_Tests>();
        }
    
        public int TODID { get; set; }
        public Nullable<int> OrderDetailID { get; set; }
        public Nullable<int> TestID { get; set; }
        public Nullable<int> SeqID { get; set; }
        public Nullable<int> TestTubeNo { get; set; }
        public Nullable<int> TestStatusID { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public string RawResults { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Employee_Tests> Employee_Tests { get; set; }
        public virtual Order_Details Order_Details { get; set; }
        public virtual Solvent Solvent { get; set; }
        public virtual Status Status { get; set; }
        public virtual Test Test { get; set; }
    }
}
